# This is a basic workflow to help you get started with Actions

name: buildZip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Compress/Decompress
    # You may pin to the exact commit or the version.
    # uses: somaz94/compress-decompress@908720afff6300ac9f2ad3addc3e672f43c1c28a
        uses: somaz94/compress-decompress@v1.0.3
        with:
          # Command to perform ("compress" or "decompress").
          command: compress
          # Source directory or file to compress or decompress.
          source: SentinelSyncFA
          # Destination directory or file to save the compressed or decompressed output.
          destination: SentinelSyncFA.zip
          # Compression format to use. Supported formats include zip, tar, tgz, and tbz2.
          format: zip
          # Whether to include the root folder itself in the compressed file.
          includeRoot: true
